CREATE TABLE tables (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    layout_id UUID NOT NULL,
    table_number INTEGER NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 4,
    status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE', -- Enum-like: AVAILABLE, OCCUPIED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (layout_id) REFERENCES restaurant_layouts(id) ON DELETE CASCADE
);
